name: "Dependabot: Github Actions" 

on:
  schedule:
    - cron: '23 4 * * *'
      timezone: 'Asia/Kuala_Lumpur'
    - cron: '23 1,7 * * *'
      timezone: 'Asia/Kuala_Lumpur'
  workflow_dispatch:
    inputs: 
      action:
        description: Action to run
        required: true
        type: choice
        options: 
          - autoreview
          - automerge

env:
  AUTOREVIEW_LIMIT: 20
  AUTOREVIEW_MAX_UPDATE: 5
  AUTOREVIEW_MAX_UPDATE_PER_REPO: 2
  AUTOMERGE_LIMIT: 20
  AUTOMERGE_MAX_UPDATE: 5

jobs:
  auto-review:
    if: |
      (github.event_name == 'schedule' && github.event.schedule=='23 4 * * *') ||
      (github.event_name == 'workflow_dispatch' && inputs.action == 'autoreview')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - run: npm install -g @siakhooi/gh-pr
      - name: All github actions with checks
        run: |
          gh-pr autoreview --assigned-to-me --authored-by-dependabot --label dependencies --not-yet-reviewed \
          --label github_actions \
          --limit "$AUTOREVIEW_LIMIT" \
          --max-update "$AUTOREVIEW_MAX_UPDATE" \
          --max-update-per-repo "$AUTOREVIEW_MAX_UPDATE_PER_REPO"
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_REPO_GITHUB_TOKEN }}

      - name: "github actions without checks: devcontainers"
        run: |
          gh-pr autoreview --assigned-to-me --authored-by-dependabot --label dependencies --not-yet-reviewed \
          --label github_actions --allow-no-checks --repo siakhooi/devcontainers \
          -l 5 --max-update 5 --max-update-per-repo 5
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_REPO_GITHUB_TOKEN }}

      - name: "github actions without checks: rpms"
        run: |
          gh-pr autoreview --assigned-to-me --authored-by-dependabot --label dependencies --not-yet-reviewed \
          --label github_actions --allow-no-checks --repo siakhooi/rpms \
          -l 5 --max-update 5 --max-update-per-repo 5
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_REPO_GITHUB_TOKEN }}

      - name: "github actions without checks: helm-charts"
        run: |
          gh-pr autoreview --assigned-to-me --authored-by-dependabot --label dependencies --not-yet-reviewed \
          --label github_actions --allow-no-checks --repo siakhooi/helm-charts \
          -l 5 --max-update 5 --max-update-per-repo 5
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_REPO_GITHUB_TOKEN }}

  auto-merge:
    if: |
      (github.event_name == 'schedule' && github.event.schedule=='23 1,7 * * *') ||
      (github.event_name == 'workflow_dispatch' && inputs.action == 'automerge')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - run: npm install -g @siakhooi/gh-pr
      - name: All github actions with checks
        run: |
          gh-pr automerge --assigned-to-me --authored-by-dependabot --label dependencies \
          --label github_actions \
          --limit "$AUTOMERGE_LIMIT" \
          --max-update "$AUTOMERGE_MAX_UPDATE" \
          --max-update-per-repo 1
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_REPO_GITHUB_TOKEN }}

      - name: "github actions without checks: devcontainers"
        run: |
          gh-pr automerge --assigned-to-me --authored-by-dependabot --label dependencies \
          --label github_actions --allow-no-checks --repo siakhooi/devcontainers \
          -l 5 --max-update 1 --max-update-per-repo 1
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_REPO_GITHUB_TOKEN }}

      - name: "github actions without checks: rpms"
        run: |
          gh-pr automerge --assigned-to-me --authored-by-dependabot --label dependencies \
          --label github_actions --allow-no-checks --repo siakhooi/rpms \
          -l 5 --max-update 1 --max-update-per-repo 1
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_REPO_GITHUB_TOKEN }}

      - name: "github actions without checks: helm-charts"
        run: |
          gh-pr automerge --assigned-to-me --authored-by-dependabot --label dependencies \
          --label github_actions --allow-no-checks --repo siakhooi/helm-charts \
          -l 5 --max-update 1 --max-update-per-repo 1
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_REPO_GITHUB_TOKEN }}
