name: "Dependabot: Go" 

on:
  schedule:
    - cron: '23 2,4,6 * * *'
      timezone: 'Asia/Kuala_Lumpur'
  workflow_dispatch:

env:
  AUTOREVIEW_LIMIT: 10
  AUTOREVIEW_MAX_UPDATE: 6
  AUTOREVIEW_MAX_UPDATE_PER_REPO: 2
  AUTOMERGE_LIMIT: 10
  AUTOMERGE_MAX_UPDATE: 3

jobs:
  auto-process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: "Install gh-pr"
        run: npm install -g @siakhooi/gh-pr

      - name: "Auto Merge"
        run: |
          gh-pr automerge --assigned-to-me --authored-by-dependabot --label dependencies \
          --label go \
          --limit "$AUTOMERGE_LIMIT" \
          --max-update "$AUTOMERGE_MAX_UPDATE" \
          --max-update-per-repo 1
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_REPO_GITHUB_TOKEN }}

      - name: "Auto Review: All checks"
        run: |
          gh-pr autoreview --assigned-to-me --authored-by-dependabot --label dependencies --not-yet-reviewed \
          --label go \
          --limit "$AUTOREVIEW_LIMIT" \
          --max-update "$AUTOREVIEW_MAX_UPDATE" \
          --max-update-per-repo "$AUTOREVIEW_MAX_UPDATE_PER_REPO"
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_REPO_GITHUB_TOKEN }}
