name: "Dependabot: Go" 

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  auto-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - run: npm install -g @siakhooi/gh-pr
      - run: gh-pr autoreview --assigned-to-me --authored-by-dependabot --label dependencies --not-yet-reviewed --limit 10 --label go --max-update 1 --max-update-per-repo 1
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_REPO_GITHUB_TOKEN }}
